language: node_js
node_js:
  - "4.2"
env:
  - NODE_ENV=production
before_install:
  - npm install -g tsd
  - npm install -g gulp
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
